apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-post-1137
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-post-1137
  template:
    metadata:
      labels:
        app: backend-post-1137
    spec:
      containers:
      - name: backend-post
        image: murtazahasan1/eduhub-post-1137:latest
        ports:
        - containerPort: 1140
